services:
  app:
    build: .
    command:
      sh -c " 
      python3 wait_for_db.py &&
      alembic upgrade head &&
      python3 -m uvicorn app.main:base_app --host 0.0.0.0 --port 8000 --reload"
    environment:
      MAPBOX_ACCESS_TOKEN: "pk.eyJ1Ijoia2l0bmVraXQiLCJhIjoiY2x2aWVqazM4MWd5ZzJqcDVldTgxeGs3YyJ9.KYUkM4Imga0-5U0jukxVFA"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    container_name: postgres
    image: postgres:14.8-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres_local"
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5433:5432"
    restart: always

  migration:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: "no"
